### ISSUE TITLE
Alive and Dead Code

### ISSUE THREAD

**Issue by Steev93** [LibsHungergames/LibsHungergames#17]
`22.05 23:31:38 [Multicraft] Skipped 151 lines due to rate limit (30/s)
22.05 23:31:37 [Server] INFO at me.libraryaddict.Hungergames.Configs.MySqlConfig.<init>(MySqlConfig.java:28) [LibsHungergames.jar:?]
22.05 23:31:37 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:179) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
22.05 23:31:37 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
22.05 23:31:37 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:184) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
22.05 23:31:37 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
22.05 23:31:37 [Server] INFO ^
22.05 23:31:37 [Server] INFO prefixWhenAlive: &b%Name%&r: %Message%
22.05 23:31:37 [Server] INFO in 'string', line 52, column 20:
22.05 23:31:37 [Server] INFO found character % '%' that cannot start any token. (Do not use % for indentation)
22.05 23:31:37 [Server] INFO org.bukkit.configuration.InvalidConfigurationException: while scanning for the next token
22.05 23:31:37 [Server] INFO [23:31:37 ERROR]: Cannot load plugins/LibsHungergames/config.yml`

Issue with this:
prefixWhenAlive: &b%Name%&r: %Message%

**Comment by Steev93** [comment]
Fixed Sorry!

Anyway to stop Ocean biomes generating ?

**Comment by Techcable** [comment]
I think there is a map config file?

**Comment by Steev93** [comment]
Yeah but how do you use it ? i like in auto generating but it's weird when only spawns in middle of ocean.

Also insted of kicking any why i could get it to move everyone to another server in /servers on a kick ?
